os: Visual Studio 2015

platform: x64

configuration: Release

environment:
    MINICONDA_ROOT: C:\Miniconda36-x64
    NSIS_ROOT: C:\Program Files (x86)\NSIS
    BOOST_ROOT: C:\Libraries\boost_1_65_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_65_0\lib64-msvc-14.0
    PATH: "%BOOST_LIBRARYDIR%;%PATH%"
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
 
install:
  - git submodule update --init --recursive

  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  - ps: choco install -y --no-progress -r swig --version 3.0.9
  - ps: choco install -y --no-progress -r sqlite --version 3.19.2
  - ps: choco install -y --no-progress -r pkgconfiglite # TODO can we get rid of this dependency?
  
  - ps: Start-FileDownload 'https://github.com/pairinteraction/pairinteraction-build-dependencies/releases/download/1528914514/cpp-libraries-windows-x86_64.zip'
  - cmd: 7z x -y cpp-libraries-windows-x86_64.zip > nul

  - ps: Start-FileDownload 'https://github.com/pairinteraction/pairinteraction-build-dependencies/releases/download/1528914514/python-packages-windows-x86_64.zip'
  - cmd: 7z x -y python-packages-windows-x86_64.zip > nul
  - cmd: call %MINICONDA_ROOT%\Scripts\activate.bat
  - cmd: conda config --prepend channels file:///%APPVEYOR_BUILD_FOLDER%/conda-export
  - cmd: conda install -y -q pairinteraction-dependencies
  - cmd: pip install git+https://github.com/pyinstaller/pyinstaller.git@5b6288b4e6c594dd695a2bd5db67aa260b771ce5 # TODO if new version that supports python 3.6 in conda-forge, specify version of pyinstaller and include pyinstaller in conda-export 
 
cache:
  - C:\ProgramData\chocolatey\bin -> .appveyor.yml
  - C:\ProgramData\chocolatey\lib -> .appveyor.yml

before_build:
  - cmd: md build && cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" .. -DCMAKE_BUILD_TYPE="%CONFIGURATION%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DWITH_DOCS=FALSE -DCMAKE_TOOLCHAIN_FILE=vcpkg-export\scripts\buildsystems\vcpkg.cmake"

build_script:
  - cmd: cmake --build . --config "%CONFIGURATION%"
  
after_build:
  - cmd: cmake --build . --target win32 --config "%CONFIGURATION%"

test_script:
  - cmd: xcopy libpairinteraction\Release\* libpairinteraction
  - cmd: cmake --build . --target check --config "%CONFIGURATION%"

artifacts:
  - path: build\pairinteraction-install-windows.exe
    name: installer

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
