os: Visual Studio 2015

platform: x64

configuration: Release

environment:
    MINICONDA_ROOT: C:\Miniconda36-x64
    NSIS_ROOT: C:\Program Files (x86)\NSIS
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
 
install:
  - git submodule update --init --recursive

  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  - ps: choco install -y --no-progress -r swig --version 3.0.9
  - ps: choco install -y --no-progress -r sqlite --version 3.19.2
  - ps: choco install -y --no-progress -r pkgconfiglite # TODO can we get rid of this dependency?
  
  - ps: Start-FileDownload 'https://github.com/pairinteraction/pairinteraction-build-dependencies/releases/download/1500989872/cpp-libraries-windows-x86_64.zip'
  - cmd: 7z x -y cpp-libraries-windows-x86_64.zip > nul

  - ps: Start-FileDownload 'https://github.com/pairinteraction/pairinteraction-build-dependencies/releases/download/1500989872/python-packages-windows-x86_64.zip'
  - cmd: 7z x -y python-packages-windows-x86_64.zip > nul
  - cmd: call %MINICONDA_ROOT%\Scripts\activate.bat
  - cmd: conda config --prepend channels file:///%APPVEYOR_BUILD_FOLDER%/conda-export
  - cmd: conda install -y -q pairinteraction-dependencies
  - cmd: pip install git+https://github.com/pyinstaller/pyinstaller.git@5b6288b4e6c594dd695a2bd5db67aa260b771ce5 # TODO if new version that supports python 3.6 in conda-forge, specify version of pyinstaller and include pyinstaller in conda-export 
 
cache:
  - C:\ProgramData\chocolatey\bin -> .appveyor.yml
  - C:\ProgramData\chocolatey\lib -> .appveyor.yml

before_build:
  - cmd: md build && cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DWITH_DOCS=FALSE -DCMAKE_TOOLCHAIN_FILE=vcpkg-export\scripts\buildsystems\vcpkg.cmake"

build_script:
  - cmd: msbuild %APPVEYOR_BUILD_FOLDER%\build\pairinteraction.sln /m /verbosity:minimal
  - cmd: msbuild %APPVEYOR_BUILD_FOLDER%\build\win32\win32.vcxproj /m /verbosity:minimal

after_build:
  - cmd: md pairinteraction-install\libpairinteraction\databases
  - cmd: md pairinteraction-install\gui
  - cmd: copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\1033\vcredist_x64.exe" pairinteraction-install\
  - cmd: xcopy /E dist\pairinteraction\. pairinteraction-install\gui
  - cmd: copy libpairinteraction\Release pairinteraction-install\libpairinteraction
  - cmd: copy libpairinteraction\pireal.py pairinteraction-install\libpairinteraction
  - cmd: copy libpairinteraction\picomplex.py pairinteraction-install\libpairinteraction
  - cmd: copy libpairinteraction\databases\quantum_defects.db pairinteraction-install\libpairinteraction\databases
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\gsl.dll pairinteraction-install\libpairinteraction
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\gslcblas.dll pairinteraction-install\libpairinteraction
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\libzmq.dll pairinteraction-install\libpairinteraction
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\sqlite3.dll pairinteraction-install\libpairinteraction
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\boost_filesystem-vc140-mt-1_64.dll pairinteraction-install\libpairinteraction
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\boost_program_options-vc140-mt-1_64.dll pairinteraction-install\libpairinteraction
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\boost_serialization-vc140-mt-1_64.dll pairinteraction-install\libpairinteraction
  - cmd: copy ..\vcpkg-export\installed\x64-windows\bin\boost_system-vc140-mt-1_64.dll pairinteraction-install\libpairinteraction
  - cmd: 7z a -tzip pairinteraction-install-windows-x86_64.zip pairinteraction-install > nul

artifacts:
  - path: build\pairinteraction-install-windows.exe
    name: installer

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
