os: Visual Studio 2015

platform: x64

configuration: Release

environment:
    MINICONDA_ROOT: C:\Miniconda36-x64
    NSIS_ROOT: C:\Program Files (x86)\NSIS
    BOOST_ROOT: C:\Libraries\boost_1_66_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_66_0\lib64-msvc-14.0
    PATH: "%BOOST_LIBRARYDIR%;%PATH%"
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
 
install:
  - git submodule update --init --recursive

  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  - ps: choco install -y --no-progress --allow-empty-checksums -r swig --version 3.0.9
  - ps: choco install -y --no-progress --allow-empty-checksums -r sqlite --version 3.19.2
  - ps: choco install -y --no-progress --allow-empty-checksums -r pkgconfiglite # TODO can we get rid of this dependency?
  
  - ps: Start-FileDownload 'https://github.com/pairinteraction/pairinteraction-build-dependencies/releases/download/1528914514/cpp-libraries-windows-x86_64.zip'
  - cmd: 7z x -y cpp-libraries-windows-x86_64.zip > nul

  - ps: Start-FileDownload 'https://github.com/pairinteraction/pairinteraction-build-dependencies/releases/download/1528914514/python-packages-windows-x86_64.zip'
  - cmd: 7z x -y python-packages-windows-x86_64.zip > nul
  - call "%MINICONDA_ROOT%\Scripts\activate.bat" root
  - cmd: conda config --prepend channels file:///%APPVEYOR_BUILD_FOLDER%/conda-export
  - cmd: conda install -y -q twine pairinteraction-dependencies
  - cmd: conda update -y -q setuptools wheel
  - cmd: pip install git+https://github.com/pyinstaller/pyinstaller.git@5b6288b4e6c594dd695a2bd5db67aa260b771ce5 # TODO if new version that supports python 3.6 in conda-forge, specify version of pyinstaller and include pyinstaller in conda-export 
 
cache:
  - C:\ProgramData\chocolatey\bin -> .appveyor.yml
  - C:\ProgramData\chocolatey\lib -> .appveyor.yml

before_build:
  - cmd: conda deactivate
  - call "%MINICONDA_ROOT%\Scripts\activate.bat" root
  - cmd: md build && cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" .. -DCMAKE_BUILD_TYPE="%CONFIGURATION%" -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DWITH_DOCS=FALSE -DCMAKE_TOOLCHAIN_FILE=vcpkg-export\scripts\buildsystems\vcpkg.cmake"

build_script:
  - cmd: conda deactivate
  - call "%MINICONDA_ROOT%\Scripts\activate.bat" root
  - cmd: cmake --build . --config "%CONFIGURATION%"
  
after_build:
  - cmd: conda deactivate
  - call "%MINICONDA_ROOT%\Scripts\activate.bat" root
  - cmd: copy %BOOST_LIBRARYDIR%\boost_filesystem-vc140-mt-x64-*.dll pairinteraction\Release
  - cmd: copy %BOOST_LIBRARYDIR%\boost_program_options-vc140-mt-x64-*.dll pairinteraction\Release
  - cmd: copy %BOOST_LIBRARYDIR%\boost_serialization-vc140-mt-x64-*.dll pairinteraction\Release
  - cmd: copy %BOOST_LIBRARYDIR%\boost_system-vc140-mt-x64-*.dll pairinteraction\Release
  - cmd: cmake --build . --target win32 --config "%CONFIGURATION%"
  - cmd: python setup.py bdist_wheel --python-tag py3 --plat-name win_amd64
  - ps: $env:PATH_WHEEL_UNMODIFIED=$(ls dist\*.whl | foreach { $_.FullName })
  - cmd: wheel unpack %PATH_WHEEL_UNMODIFIED% -d wheelhouse\
  - ps: $env:PATH_WHEEL_UNPACKED=$(ls wheelhouse\* | foreach { $_.FullName })
  - cmd: xcopy pairinteraction\Release\* %PATH_WHEEL_UNPACKED%\pairinteraction\
  - ps: Remove-Item –path $env:PATH_WHEEL_UNPACKED\*.dist-info\RECORD
  - cmd: wheel pack %PATH_WHEEL_UNPACKED% -d wheelhouse\

test_script:
  - cmd: xcopy pairinteraction\Release\* pairinteraction
  - cmd: cmake --build . --target check --config "%CONFIGURATION%"

artifacts:
  - path: build\pairinteraction-install-windows.exe
    name: installer

after_test:
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_NAME -eq "pairinteraction/pairinteraction") { Invoke-Expression "twine upload --username pairinteraction-slave --password $env:PYPI_TOKEN --skip-existing $env:APPVEYOR_BUILD_FOLDER\build\wheelhouse\*.whl;" }
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_NAME -ne "pairinteraction/pairinteraction") { Invoke-Expression "twine upload --username pairinteraction-slave --password $env:PYPI_TOKEN --skip-existing --repository-url https://test.pypi.org/legacy/ $env:APPVEYOR_BUILD_FOLDER\build\wheelhouse\*.whl;" }

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true
