language: generic

matrix:
  include:
    - os: linux
      services: docker
      env: image=ubuntu:14.04
      script: docker run -v $TRAVIS_BUILD_DIR:/travis -it pairinteraction/$image /bin/bash -x -c "cd /travis && mkdir build && cd build && cmake .. && make"
    - os: linux
      services: docker
      env: image=ubuntu:16.04
      script: docker run -v $TRAVIS_BUILD_DIR:/travis -it pairinteraction/$image /bin/bash -x -c "cd /travis && mkdir build && cd build && cmake .. && make"
    - os: linux
      services: docker
      env: image=opensuse:13.2
      script: docker run -v $TRAVIS_BUILD_DIR:/travis -it pairinteraction/$image /bin/bash -x -c "cd /travis && mkdir build && cd build && cmake .. && make"
    - os: linux
      services: docker
      env: image=opensuse:13.2-w64
      script: docker run -v $TRAVIS_BUILD_DIR:/travis -it pairinteraction/$image /bin/bash -x -c "cd /travis && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw64.cmake .. && make"
    - os: osx
      osx_image: xcode8
      before_script: brew install eigen pyqt5 gsl openmpi
      script: mkdir build && cd build && cmake .. && make
